### ISSUE TITLE
[StripeSubscriptionPlugin] Incoming webhook is missing metadata.orderCode, cannot process this event

### ISSUE THREAD

**Issue by yackinn** [Pinelab-studio/pinelab-vendure-plugins#100]
**Which plugin is the issue about?**
stripe-subscription-plugin

**Describe the bug**
When creating a subscription intent via createStripeSubscriptionIntent an error is logged.
<img width="1224" alt="Bildschirm­foto 2023-02-13 um 20 26 48" src="https://user-images.githubusercontent.com/61085055/218554774-ba332b2a-b2e5-4212-94fe-bdbb008f73fa.png">

The active order object seems correct to me.
[active-order.json.zip](https://github.com/Pinelab-studio/pinelab-vendure-plugins/files/10725593/active-order.json.zip)

**To Reproduce**

1. Use a non subscription product. A normal one time payment product.
2. Supply all necessary data for a valid active order
3. call mutation
	mutation CreateStripeSubscriptionIntent {
	  createStripeSubscriptionIntent
	}

**Expected behavior**
A valid payment intent should be created without any error

**Screenshots**

**Environment**

- Vendure version: 2.0.0-next.28
- Plugin version "vendure-plugin-stripe-subscription": "5.0.2"
- Database postgres

**Additional context**

**Comment by yackinn** [comment]
Do you need more information on this issue? Can I support debugging?

**Comment by martijnvdbrug** [comment]
Hi @yackinn, Thanks for the report.

I see that the webhook event is `customer.created`. This will probably not have metadata.ordercode, but thats expected. Even though the plugin should handle this case, you can solve it now by configuring only these events for your webhook in Stripe: 
https://github.com/Pinelab-studio/pinelab-vendure-plugins/tree/master/packages/vendure-plugin-stripe-subscription#setup-stripe-webhook

From what I can see from your logs, is that the payment intent is created successfully. Do you receive something like `pi_xxx_secret_xxx` from the createPaymentIntent mutation? If so, that means the intent is created, and you can use this secret to provision a checkout form on your storefront.

**Comment by yackinn** [comment]
That works.
For anyone seeing a similar error use this tunnel config.

`stripe listen --forward-to localhost:3000/stripe-subscriptions/webhook -e=payment_intent.succeeded,invoice.payment_succeeded,invoice.payment_failed`

**Comment by yackinn** [comment]
The purchased product variant isn't a subscription product though.
This error is displayed.
Is it possible to purchase non subscription products with the plugin?

<img width="1697" alt="Bildschirm­foto 2023-02-24 um 12 42 20" src="https://user-images.githubusercontent.com/61085055/221170884-40081019-4e8b-4dd1-afa4-e9eedc2c03c3.png">

**Comment by martijnvdbrug** [comment]
Jep, it's just a warning. Everything should work fine. The plugin tries to create subscriptions for your product, but it shoudln't

But, as stated above: I will also fix this logging, as it should not bug you with warnings when everything works as expected.

**Comment by martijnvdbrug** [comment]
Closing this in favor of https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/108
