### ISSUE TITLE
Webhook deliver getting failed in Stripe

### ISSUE THREAD

**Issue by tufail** [Pinelab-studio/pinelab-vendure-plugins#102]
**Which plugin is the issue about?**
payment/stripe-plugin

**Describe the bug**
After payment is succeeded , the webhook is getting failed.

**To Reproduce**

1. Add surcharge to Cart and no lineItems (lineItems: [])
2. Click on checkout
3. Complete shipping and delivery Mutation
4. Fill stripe card details
5. Click on Pay/Complete Payment 

**Expected behavior**
After succeeding the payment should change the order status to "Payment settled" but the status is still "Adding items".
We have checked the stripe log and there payment we have received but webhook got failed. 

 
**Environment**

- Vendure version: 1.9.0
- Plugin version 1.9.0
- Database  MySQL 

**Additional context**
If we are adding at least one product in checkout/activeOrder data, the webhook is triggering and there is no issue. It is only failing  if we are trying to pay only for surcharge without any item in the cart.

**Comment by tufail** [comment]
Hi @martijnvdbrug 
I am getting error as below in  log
```[StripePlugin] Error transitioning order 8GNE48SBL7CRC78F to ArrangingPayment state: ORDER_STATE_TRANSITION_ERROR```

**Comment by martijnvdbrug** [comment]
@tufail we were indeed not using the surcharges, that issue is now resolved and published as version [5.2.3](https://www.npmjs.com/package/vendure-plugin-stripe-subscription/v/5.2.3)
