### ISSUE TITLE
New plugin: vendure-plugin-sales-per-variant

### ISSUE THREAD

**Issue by martijnvdbrug** [Pinelab-studio/pinelab-vendure-plugins#136]
**Is your feature request related to a problem? Please describe.**
I would like to view the nr. of sold product variants per month.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/6604455/233617679-7f965b2c-f7fb-4bb4-95c9-ded58ae04a1d.png)

An administrator can select a product variant to view the details of the last month. 

**Describe alternatives you've considered**
-

**Additional context**
- [ ] Create a query `soldVariantsPerMonth(variantId: ID!)` that returns the nr of sales of that variant per month, for the past 12 months
- [ ] Please be aware of performance, as querying placed orders for the past 12 months can get quite heavy: Optimize database queries (similar to popularity-scores) and use inMemoryCaching where possible (see metrics plugin)
- [ ] You can reuse admin logic from Metrics plugin for the diagram.

**Comment by is0utfitters** [comment]
It would be valuable to list out all of the products and append their variants so that a user can select all product variants sold during the period as well as the specific variant if desired:
Shoes
Shoes - Red
Shoes - White
Shirts
Shirts - Yellow
Shirts - Blue
etc...

**Comment by martijnvdbrug** [comment]
Done and merged in https://github.com/Pinelab-studio/pinelab-vendure-plugins/issues/140
