### ISSUE TITLE
Stripe Subscriptions: Early Billing Option

### ISSUE THREAD

**Issue by is0utfitters** [Pinelab-studio/pinelab-vendure-plugins#141]
**Is your feature request related to a problem? Please describe.**
Say I have a class for $300 with a $30 registration fee that can be paid for over 3 months - but I want to bill earlier than the start of the class:
Duration: June 1st - End of August
Billing: Monthly billing, starting on May 1st

The problem is that if someone signs up for the class on the 5th of May, they are now only billed a pro-rated amount until the actual start of the class on June 1st and the final 3 months rather than the full payment for the 1st month.

**Describe the solution you'd like**
A way to charge the full billing cycle during the interim period between billing start and duration start but pro-rate after duration start.

**Describe alternatives you've considered**
If there is a fixed start date for billing, we could add the option of a separate fixed start for the duration period?  If they are different dates, then that can be used to determine if we charge the full billing cycle or use proration based on when the order is placed: if before the duration start, then the amount due at checkout would be the registration amount + any months of billing due already.

**Additional context**
We would need to keep in mind the application of discount codes and how they would apply to future payments.

**Comment by martijnvdbrug** [comment]
Closing this for now, as we've gone a new direction with the Stripe Subscription plugin. @is0utfitters Feel free to reopen or re-discuss this in context of the updated plugin!
