### ISSUE TITLE
error TS2305: Module '"vendure-plugin-webhook"' has no exported member 'webhookAdminUi'.

### ISSUE THREAD

**Issue by kyssaFarms** [Pinelab-studio/pinelab-vendure-plugins#17]
Not being able to compile the admin UI even though i have added the vendure-plugin-webhook with yarn

**Comment by martijnvdbrug** [comment]
There was an error in the Readme. You need to use `WebhookPlugin.ui` to compile the admin UI.

It was fixed in https://github.com/Pinelab-studio/pinelab-vendure-plugins/commit/d1f510a0bde2f9a3c364230b239682ecd9ef494b and published under v2.4.1
