### ISSUE TITLE
[V2.0.4] productVariantsWithLowStock is deprecated for Vendure V2

### ISSUE THREAD

**Issue by tianyingchun** [Pinelab-studio/pinelab-vendure-plugins#197]
**Which plugin/repository is the issue about?**
`vendure-plugin-stock-monitoring`

**Describe the bug**

**To Reproduce**
resoler `productVariantsWithLowStock`
cause of vendure V2 changed `stockOnhand` it will throw error 
` Cannot read properties of undefined (reading 'databaseName')`
```ts
 @Query()
  @Allow(Permission.ReadCatalog)
  async productVariantsWithLowStock(
    @Ctx() ctx: RequestContext
  ): Promise<ProductVariant[]> {
    return this.connection
      .getRepository(ctx, ProductVariant)
      .createQueryBuilder('variant')
      .leftJoin('variant.product', 'product')
      .leftJoin('product.channels', 'channel')
      .where('variant.enabled = true')
      .andWhere('variant.stockOnHand < :threshold', {
        threshold: StockMonitoringPlugin.threshold,
      })
      .andWhere('variant.deletedAt IS NULL')
      .andWhere('channel.id = :channelId', { channelId: ctx.channelId })
      .limit(50)
      .orderBy('variant.stockOnHand', 'ASC')
      .getMany();
  }
```
need to be refactor.
**Expected behavior**

**Screenshots**

**Environment**

- NodeJS version 18
- Vendure version: 2.0.4
- Plugin version :lastest
- Database: mysql
- Any other version numbers from the environment you're using

**Additional context**

**Comment by martijnvdbrug** [comment]
Hi @tianyingchun,

Thank you for the report. This plugin is indeed not ready for V2 yet, we are in the midst of upgrading all of our plugins to V2. Contributions are welcome of course!
