### ISSUE TITLE
Metrics Plugin labels not showing

### ISSUE THREAD

**Issue by jacobfrantz1** [Pinelab-studio/pinelab-vendure-plugins#251]
**Which plugin/repository is the issue about?**
metrics-plugin

**Describe the bug**
Labels tend to not show and are wrong when they do.
vdr-chart uses a dateformatter internally for the label

```
const tooltipText = `
            <div class="tooltip-date">${dateFormatter.format(new Date(meta.label))}</div>
            <div class="tooltip-value">${formattedValue}</div>
           `;
```

**To Reproduce**

Hover over metrics
See that tooltip is not showing, and console is full of "ERROR RangeError: Invalid time value"

**Expected behavior**
Label should show on hover

**Environment**
- NodeJS version: 16.20
- Vendure version: 2.0.6
- Plugin version 7.1.2
- Database postgresql 14

**Comment by martijnvdbrug** [comment]
Hi! Thanks for your report. Have you tried the latest version of @pinelab/vendure-plugin-metrics? There has been a bit of an overhaul, and I think this os fixed
