### ISSUE TITLE
vendure-plugin-invoices shows typescript error Property 'upsertInvoiceConfig' does not exist on type 'UpsertInvoiceConfigMutation | undefined 

### ISSUE THREAD

**Issue by miteshjethmalani** [Pinelab-studio/pinelab-vendure-plugins#261]
**Which plugin/repository is the issue about?**
[ invoices]

**Describe the bug**
The error while running the admin UI shows error Property 'upsertInvoiceConfig' does not exist on type 'UpsertInvoiceConfigMutation | undefined.

**To Reproduce**

1. Install vendure.
2. Run yarn add vendure-plugin-invoices
3. migrate and then check the command line
4. See error mentioned above

**Expected behavior**
There should not be any typescript error.

**Environment**

- NodeJS version v18.17.1
- Vendure version: 2.0.6/2.0.7
- Plugin version 7.0.0
- Database Postgres

**Comment by huwgit** [comment]
I got this error today too - any solution?

**Comment by martijnvdbrug** [comment]
Hi, thanks for the error report. I see that you are using v7.0.0, that's [a deprecated version](https://www.npmjs.com/package/vendure-plugin-invoices). Could you the latest version of [this package](https://www.npmjs.com/package/@pinelab/vendure-plugin-invoices), and see if the issue still persists?
