### ISSUE TITLE
Popularity Scores calculation when a collections exists with no variatns

### ISSUE THREAD

**Issue by dalyathan** [Pinelab-studio/pinelab-vendure-plugins#279]
**Which plugin/repository is the issue about?**
vendure-plugin-popularity-scores
**Describe the bug**
Trying to calculate popularity scores for products  and collection per channel throws error. 
**To Reproduce**

1. Open your browser
2. Try to calculate popularity scores by typing `/popularity-scores/calculate-scores/:mychanneltoken/:secret`

**Expected behavior**
Popularity score should be there for collections and products. 

**Environment**

- NodeJS version 20.9.1
- Vendure version: [e.g. 1.7.1] 2.0.9
- Plugin version 1.1.0
- Database [e.g. MySQL] Postgresql
- Any other version numbers from the environment you're using

**Additional context**
The line that seems to be throwing the error is [this](https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/31ae5c3a34feb5439894e9eef3f7f284ee2c5d56/packages/vendure-plugin-popularity-scores/src/sort.service.ts#L144). When all the `collections` being processed have product variants, everything seems to be working fine. But for those `collections` with variants, `uniqueProductIds` will be empty which causes TypeORM to throw an error.

**Comment by martijnvdbrug** [comment]
Done
