### ISSUE TITLE
Stripe Subscription Plugin 2.1 throws error when using incorrect api keys

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#285]
**Which plugin/repository is the issue about?**
vendure-plugin-stripe-subscription

**Describe the bug**
[This line](https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/985a9e6ffd5cec67d1a3a4d924c9bd4bf7faa982/packages/vendure-plugin-stripe-subscription/src/api/stripe-subscription.service.ts#L202) registers the webhooks for the stripe subscription service. It requires a valid API key, otherwise it throws an error. This is a problem in development or test scenario's where valid api keys may not be available.

In our case, this line triggers when we disable the dummy payment method. 

**To Reproduce**

1. create your stripe payment methods with invalid api keys
2. disabled the dummy payment handler:

```
    await client.query(UPDATE_PAYMENT_METHOD, {
        input: {
            id: 1,
            enabled: false,
        }
```

**Expected behavior**
The code should warn instead of throw here. 

**Environment**

- NodeJS version: 18.x
- Vendure version: 2.1.2
- Plugin version: 2.1.0
- Database: postgres
- Any other version numbers from the environment you're using

**Comment by mschipperheyn** [comment]
Nope, this also happens with correct .env keys.

**Comment by martijnvdbrug** [comment]
Hi @mschipperheyn, thanks for the report. Are you sure you are using the latest version? I can't reproduce, and the published code also says it's catching any errors and just logging an error:

[Checkout line 100 of the published codde of v2.1.0 here ](https://www.npmjs.com/package/@pinelab/vendure-plugin-stripe-subscription?activeTab=code)

**Comment by mschipperheyn** [comment]
Thanks for the follow up. Yes, I am. But I see that there is a new version out. Let me have a go with that and I'll let you know what happens

**Comment by martijnvdbrug** [comment]
Assuming this is closes, as we haven't discussed this in our weekly call for a while. Feel free to re-open if the issue still persists
