### ISSUE TITLE
Getting data from Webhook 

### ISSUE THREAD

**Issue by orjanskaar** [Pinelab-studio/pinelab-vendure-plugins#30]
Hi

I've managed to get my webhook firing for the "StockMovementEvent" using the POST method
```javascript
WebhookPlugin.init({
    httpMethod: 'POST',
    delay: 3000, // Optional if you want to wait for more events
    events: [ProductOptionEvent, ProductVariantChannelEvent, ProductVariantEvent, StockMovementEvent],
})
```
I only get an empty string on "request.body". (Like the readme hints to)

Is there some way to configure  what data to send like the current stock balance?

**Comment by martijnvdbrug** [comment]
https://github.com/vendure-ecommerce/vendure/discussions/1739

**Comment by orjanskaar** [comment]
Hello

I would love to try and help out and give it a go, but im am pretty shure this is just beyond my programming capabilities right now. 
So any help would be apreciated.

**Comment by martijnvdbrug** [comment]
@orjanskaar [`vendure-plugin-webhook` v3.12.0](https://www.npmjs.com/package/vendure-plugin-webhook) now allows you to define a POST body (and headers) via a custom function:
```ts
WebhookPlugin.init({
    httpMethod: 'POST',
    events: [ProductEvent, ProductVariantChannelEvent, ProductVariantEvent],
    requestFn: (event) => {
      return {
        headers: { test: '1234' },
        body: JSON.stringify({ createdAt: event.createdAt }),
      };
    },
  }),
```

Let me know if you have any questions. 

Closed in https://github.com/Pinelab-studio/pinelab-vendure-plugins/pull/52
