### ISSUE TITLE
Parameter Binding Error in PopularityScoresPlugin with Large Dataset in Vendure

### ISSUE THREAD

**Issue by asonnleitner** [Pinelab-studio/pinelab-vendure-plugins#303]
**Which plugin/repository is the issue about?**
popularity-scores

**Describe the bug**
The popularity-scores encounters a critical error during the 'calculate-popularity-scores' job. The error, "bind message has 19728 parameter formats but 0 parameters," suggests a problem with query parameter binding. This issue causes intermittent job failures (e.g., attempts 3 and 4 of 6). The scale of the data (156821 products, 4221 collections, 6377 order lines, and 3203752 product variants) might be contributing to the complexity of the situation.

**To Reproduce**

1. Deploy the Vendure worker with the PopularityScoresPlugin enabled in an environment with a large dataset (156821 products, 4221 collections, 6377 order lines, 3203752 product variants).
2. Trigger the 'calculate-popularity-scores' job.
3. Observe the logs for the parameter binding error.

**Expected behavior**
The 'calculate-popularity-scores' job should complete successfully, handling large datasets without errors related to parameter binding in SQL queries.

**Environment**

- NodeJS version [20]
- Vendure version: [^2.1.4]
- Plugin version [^1.4.0]
- Database [PostgreSQL]

**Additional context**
The error "bind message has 19728 parameter formats but 0 parameters" indicates an issue with SQL query preparation or execution within the plugin, particularly in handling large data volumes. The issue might be related to how the plugin constructs SQL queries, manages database connections, or handles large sets of parameters. Despite slow query log entries, the primary concern here is the parameter binding error in the context of a large-scale Vendure deployment.

**Comment by martijnvdbrug** [comment]
Hi, sorry for the late response, and thanks for your issue report.

Is there any way you can create a minimal reproduction? I.e. with a script that adds a large number of dummy products, or something else that makes it easier for us to reproduce?

I've tested this with ~500 dummy products, but that seems to work fine, so it's a bit hard to debug this right now.

**Comment by martijnvdbrug** [comment]
I found this: https://github.com/typeorm/typeorm/issues/3044#issuecomment-451517241

The issue is this line: https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/41bad0db4ace6ab45eb8c3797f3fafc52e8e5605/packages/vendure-plugin-popularity-scores/src/sort.service.ts#L145

There are too many product ID's to fetch in one query. @dalyathan can you pick this up?
