### ISSUE TITLE
RequestTransformer is not exported in @pinelab/vendure-plugin-webhook

### ISSUE THREAD

**Issue by brmk** [Pinelab-studio/pinelab-vendure-plugins#306]
**Which plugin/repository is the issue about?**
@pinelab/vendure-plugin-webhook

**Describe the bug**
Module '"@pinelab/vendure-plugin-webhook"' has no exported member 'RequestTransformer'.

**To Reproduce**

1. Install the latest @pinelab/vendure-plugin-webhook
2. Create a new RequestTranformer based on an example in the docs

```
import { Logger, ProductEvent } from '@vendure/core';
import { RequestTransformer } from '@pinelab/vendure-plugin-webhook';

export const stringifyProductTransformer = new RequestTransformer({
  name: 'Stringify Product events',
  supportedEvents: [ProductEvent],
  transform: (event, injector) => {
    if (event instanceof ProductEvent) {
      return {
        body: JSON.stringify(event),
        headers: {
          'x-custom-header': 'custom-example-header',
          'content-type': 'application/json',
        },
      };
    } else {
      throw Error(`This transformer is only for ProductEvents!`);
    }
  },
});

// In your vendure-config's plugin array:
WebhookPlugin.init({
  events: [ProductEvent],
  requestTransformers: [stringifyProductTransformer],
});
```

**Expected behavior**
RequestTransformer is exported from the plugin

**Screenshots**
-

**Environment**

- NodeJS version: v18.10.0
- Vendure version: 2.1.4
- Plugin version: 1.1.0
- Database: any

**Additional context**
-

**Comment by martijnvdbrug** [comment]
Fixed in v1.1.1
