### ISSUE TITLE
Anonymized order plugin exposes customer details

### ISSUE THREAD

**Issue by martijnvdbrug** [Pinelab-studio/pinelab-vendure-plugins#316]
**Which plugin/repository is the issue about?**
[anonymized-order]

**Describe the bug**
We filter out an orders sensitive information like `shippingAddress` and `customer`, but with a nested query we can, for example get all orders of a customer.

**To Reproduce**
Query an anonymized order with the following query:

```graphql
{
  anonymizedOrder(orderCode:"CG-201023-UBN8K", emailAddress:"martijn@pinelab.studio") {
    id
    createdAt
    updatedAt
    lines {
      id
      order {
        customer {
          firstName
          lastName
          orders {
            items {
              id
              code
            }
          }
        }
      }
    }
  }
}
```
This exposes all orders of a customer, including all sensitive details!

**Expected behavior**
The sensitive fields should not be exposed. We should also nullify `order.lines.order`. Are there any other fields that can cause this kind of unwanted data exposure?

Extra request: Can we nullify shippingAddress instead of returning an empty object? It's an optional field on an order, so we can just set it to undefined or null

**Comment by dalyathan** [comment]
yes, nullifying order.lines.order will do the trick. I will look to see if there are any more fields that could expose sensitive data.
I don't think we can nullify shippingAddress as it is a non-nullable field for Order. I tried and ts complained
