### ISSUE TITLE
Extract modify-custom-orders-service to service class 

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#343]
**Is your feature request related to a problem? Please describe.**
Currently, the service logic of the modify-custom-order-plugin is contained in the resolver. This makes it impossible to use the service from other plugins. By extracting the logic into a service class, and referencing that in the plugin, it would become injectable in other service classes

**Describe the solution you'd like**
see above

**Describe alternatives you've considered**
Inlining the code

**Additional context**
I'm trying to transition orders within the context of another plugin

**Comment by martijnvdbrug** [comment]
Good point! Released as 1.2.0
