### ISSUE TITLE
Invoices plugin improvements

### ISSUE THREAD

**Issue by martijnvdbrug** [Pinelab-studio/pinelab-vendure-plugins#352]
After using the invoices plugin for one of our clients, I think we can improve the UI a bit:

* Can we remove the outer according that says `Settings`? This was used because it was shown together with a list of invoices. Now, in V2 it's a dedicated settings page, so it doesn't make sense to have it collapsable
* Can we put the form fields and buttons in a container, to make it more consistent with Vendure's styling. See the attached screenshot  of Global Settings. All detail screens have the same basic layout
   * Move `save` button to the top right and rename to `update`
* Can we make the order-code optional? If no order code is given, we should get the latest placed order.
* Remove the Preview tooltip. It's description isn't accurate anymore. We can rename the button to 'Preview template'
* We should keep the preview button close to the template and close to the orderCode field, so that it's clear those are all related to eachother.

![Image](https://github.com/Pinelab-studio/pinelab-vendure-plugins/assets/6604455/ba9d1a06-d5f2-4476-8d7c-c23e323ad310)

![Image](https://github.com/Pinelab-studio/pinelab-vendure-plugins/assets/6604455/aa0f4a3b-be3d-4975-a9cc-07ca3fa2f693)

**Comment by martijnvdbrug** [comment]
@dalyathan Is this one already ready for review? I cant seem to find the related PR?

**Comment by dalyathan** [comment]
It was actually part of the (now closed) `pinelab-admin-components-plugin` PR, but since that approach is abandoned, I will work on it
