### ISSUE TITLE
Invoice generation fails in production

### ISSUE THREAD

**Issue by ankitdev10** [Pinelab-studio/pinelab-vendure-plugins#360]
**Which plugin/repository is the issue about?**
Invoices Plugin

**Describe the bug**
Everything works locally but when running docker image i get  spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT. 

**To Reproduce**
Generate invoice either by placing an order or directly from order-detail page.

**Expected behavior**
Successful generation of invoice.

**Screenshots**

**Environment**

- NodeJS version 20.9.0
- Vendure version: 2.1.2
- Plugin version 2.0.2
- Database postgres
- Any other version numbers from the environment you're using

**Additional context**

**Comment by martijnvdbrug** [comment]
Hi, thanks for your report. Can you share your `Dockerfile`? This is the one we use in multiple projects, and that seems to work:

```
FROM node:18

# Create app directory
WORKDIR /usr/src/app

COPY . .
RUN yarn install
RUN yarn build

# PhantomJS fix https://github.com/bazelbuild/rules_closure/issues/351
ENV OPENSSL_CONF=/dev/null

# Run the web service on container startup.
CMD [ "yarn", "start" ]
```

The `ENV OPENSSL_CONF=/dev/null` might not be needed anymore, so if it works, you can try again without that line.

**Comment by ankitdev10** [comment]
Hello, we figured it out. So we were using alping image which apparently had a dependency missing for phantomjs to work correctly. Thanks for replying and the issue can be closed.

**Comment by barakamwakisha** [comment]
For anyone who might still be facing this issue, the required dependency is `fontconfig`.  See the PhantomJS [docs](https://www.npmjs.com/package/phantomjs#linux-note).
