### ISSUE TITLE
It should be possible to set isCustomerManaged in the admin for CustomerManagedGroups

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#377]
**Is your feature request related to a problem? Please describe.**
I need to be able to create a customerManagedGroup as customer manageable through the admin.

**Describe the solution you'd like**
The isCustomerManaged should be available on the customFields in the admin api for the Create/Update as well as existing get/list statements

**Describe alternatives you've considered**
hacking it myself

**Additional context**
I will add it on the plugin and submit a PR

**Comment by martijnvdbrug** [comment]
Good point, thanks Marc!
