### ISSUE TITLE
Error when calculating popularity scores for collections

### ISSUE THREAD

**Issue by sergio-irigoyen** [Pinelab-studio/pinelab-vendure-plugins#386]
**Which plugin/repository is the issue about?**
popularity-scores

**Describe the bug**
After installing the plugin and running the job, it fails with the following error:

ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'customFieldsPopularityscore' at row 1.

**To Reproduce**

1. Install the plugin
2. Call the rest endpoint to start the job

**Expected behavior**
No error.

**Environment**

- NodeJS version 18.19.0
- Vendure version: 2.1.4
- Plugin version 1.6.0
- Database MariaDB 10.11.6

**Additional context**
I investigated a bit and it seems like the score calculation is concatenating the scores as strings instead of summing them up.

When printing the score in this chunk of code, I get results like '0000000000000000250000000000000000000'

![image](https://github.com/Pinelab-studio/pinelab-vendure-plugins/assets/33727527/f81b1bff-a244-40d1-b703-0d77fc7f742e)

If I wrap the summedProductsValue.productScoreSum in a Number(), the error goes away.

![image](https://github.com/Pinelab-studio/pinelab-vendure-plugins/assets/33727527/40e3ebe7-a85b-4b1e-bade-e82fde619886)

**Comment by martijnvdbrug** [comment]
Thank you for your report! @dalyathan can  you look into this one?
