### ISSUE TITLE
Weird discounts related error on subscriptions

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#387]
**Which plugin/repository is the issue about?**
vendure-plugin-accept-blue
vendure-plugin-stripe-subscriptions

**Describe the bug**

I get an error retrieving a DRAFT order that has a subscriptions configured for it. 
We currently have both strip and accept blue configured in our system

```
[
  {
    message: 'The property "discounts" on the Order entity requires the Order.lines relation to be joined.\n' +
      "This can be done with the EntityHydratorService: `await entityHydratorService.hydrate(ctx, order, { relations: ['lines'] })`",
    locations: [ [Object] ],
    path: [ 'addItemToDraftOrder', 'lines', 0, 'acceptBlueSubscriptions' ],
    extensions: { code: 'INTERNAL_SERVER_ERROR' }
  }
]
```

**To Reproduce**
We are able to load this order in default vendure backend. But we are creating our own in React which may be getting fragments differently.

These are our fragments for this retrieval
```
fragment orderFragment on Order {
    id
    code
    type
    state
    active
    orderPlacedAt
    total

    subTotal
    subTotalWithTax
    currencyCode
    shippingWithTax
    total
    totalQuantity
    totalWithTax

    customer {
      id
      firstName
      lastName
      emailAddress
    }

    createdAt
    updatedAt
  }

fragment orderLineFragment on OrderLine {
    id
    quantity
    discountedUnitPrice
    discountedUnitPriceWithTax
    unitPrice
    unitPriceWithTax
    linePrice
    taxRate

    featuredAsset {
      preview
    }
    productVariant {
      id
      name
      isSubscription
      productId
      product {
        id
        name
      }
    }
    acceptBlueSubscriptions {
      name
      amountDueNow
      recurring {
        amount
        interval
        intervalCount
        startDate
        endDate
      }
    }
    stripeSubscriptions {
      name
      amountDueNow
      recurring {
        amount
        interval
        intervalCount
        startDate
        endDate
      }
    }
    customFields {
      downpayment
      interval
      intervalCount
      intervalStartDate
      startDate
      EndDate
      assignedCustomer {
        id
        firstName
        lastName
        age
        customFields {
          image {
            preview
          }
        }
      }
    }
  }

 fragment orderDetailFragment on Order {
    ...orderFragment
    couponCodes
    nextStates
    customer {
      id
      firstName
      lastName
      age
      addresses {
        ...addressFragment
      }
      groups {
        name
        customers {
          items {
            id
            firstName
            lastName
            age
            customFields {
              image {
                preview
              }
            }
          }
        }
      }
      customFields {
        image {
          preview
        }
      }
    }
    billingAddress {
      ...orderAddressFragment
    }
    shippingAddress {
      ...orderAddressFragment
    }
    shippingLines {
      id
      price
      priceWithTax
      discountedPrice
      discountedPriceWithTax
      shippingMethod {
        id
      }
    }
    lines {
      ...orderLineFragment
    }
    discounts {
      amount
      amountWithTax
    }
    payments {
      id
      amount
      state
      method
      metadata
      refunds {
        id
        reason
        total
      }
    }
    taxSummary{
      description
      taxRate
      taxBase
      taxTotal
    }
      
    history{
      items{
        isPublic
        id
        type
        data
        createdAt
        administrator{
          firstName
          lastName
          id
        }
      }
    }
  }

```

We have tried removing `discounts` from the retrieval since that is referenced in the error, but that makes no difference

**Expected behavior**
Well, hopefully not this issue. It seems like a field resolver type issue. Vendure does tend to presume certain key retrievals  which can create this kind of issue.

**Screenshots**

**Environment**

- NodeJS version
- Vendure version: reproduced on 2.1.8 and 2.2.0-beta.6
- Plugin version stripe: 2.4.4 accept-blue 1.1.0
- Database postgres

**Additional context**

**Comment by martijnvdbrug** [comment]
> I would be an advocate of merging these two keys into a single `subscriptions` key anyways bc the orderline should not care about the subscriptions vendor, there will always be only 1 per orderline, and the keys it provides are equal anyways,

Understanable, but this isn't possible technically: The plugin that is loaded into Vendure last will override the previous `subscriptions` resolver. So, when we would first load Stripe, then AC, all `orderline.subscriptions` queries would all go to the AC plugin, even when it should be a Stripe subscription. Can this be solved on the storefront? Something like 
```ts
subscription = orderLine.acceptBlueSubscriptions || orderLine.stripeSubscriptions
```

**Comment by mschipperheyn** [comment]
It could be a resolver that returns whatever is active? Maybe a generic wrapper that does that and is a separate plugin. It could return unsupportedError if no subscription modules are present. I didn't really think it through. But it's SO easy to fuck this up client side. Bc you have to check all over the place if you have an acceptBlueSubscription or stripSubscription

**Comment by martijnvdbrug** [comment]
@mschipperheyn You could implement a resolver like this in your own project, which then resolves `orderLine.subscriptions` based on the loaded plugin. Your customer resolver could call the `AcceptBlueResolver` or the `StripeSubscriptionResolver` in typescript

**Comment by martijnvdbrug** [comment]
Note to self: Seems related https://discord.com/channels/1100672177260478564/1100751353946587229/threads/1226845446094323723

**Comment by martijnvdbrug** [comment]
@mschipperheyn Closing this for now, because inactive issue and I cant reproduce. Please reopen if its still an issueof course!
