### ISSUE TITLE
Hydrating Order leads to removal of discounts

### ISSUE THREAD

**Issue by dalyathan** [Pinelab-studio/pinelab-vendure-plugins#417]
**Which plugin/repository is the issue about?**
`shipping-extensions`

**Describe the bug**
Hydrating the order in `weightAndCountryChecker.check` removes discounts applied to the `Order`

**To Reproduce**

**Expected behavior**
Hydrating shouldn't remove fields

**Screenshots**

**Environment**

- NodeJS version 20.8..1
- Vendure version: 2.1.5
- Plugin version 2.5.1
- Database MySQL
- Any other version numbers from the environment you're using

**Additional context**

**Comment by martijnvdbrug** [comment]
Good find!
