### ISSUE TITLE
InvoicePlugin - Error when using s3 storage that doesn't support SigV2

### ISSUE THREAD

**Issue by Conor-Burns** [Pinelab-studio/pinelab-vendure-plugins#42]
I'm getting this error as there isn't an option to enable SigV4 like in the asset server storage strategy:
![error](https://user-images.githubusercontent.com/41896852/182441945-421d3754-63eb-4ac0-bb84-7a3bd88c8d86.png)
![current](https://user-images.githubusercontent.com/41896852/182441957-31c3e0c2-6a66-4897-b98d-08a3fdb4e1da.png)
![with sig v4](https://user-images.githubusercontent.com/41896852/182441966-28f18f0f-4c76-49a6-8187-741df42b811b.png)

**Comment by martijnvdbrug** [comment]
@Conor-Burns Thanks for your contribution. This fix is published with 3.9.0 https://www.npmjs.com/package/vendure-plugin-invoices/v/3.9.0

**Comment by Conor-Burns** [comment]
Cheers :+1:
