### ISSUE TITLE
Primary collection plugin is not channel aware

### ISSUE THREAD

**Issue by martijnvdbrug** [Pinelab-studio/pinelab-vendure-plugins#456]
For the ColourGraphics project, we have assigned the same product to multiple channels. A product can however only have 1 primary collection. In this setup a product should be able to ahve 2 primary collections: 1 for CG channel and 1 primary collection for the Fabrix channel.

How can we do this? Any suggestions?

**Comment by dalyathan** [comment]
I think this is possible using  a list of json as the `Collection.customFields.primaryCollections`. The list will have the following structure:
```ts
[
 {
   channelId: string,
   collectionId: string
 }
]
```
