### ISSUE TITLE
Invoice PDF's fail to generate when using docker container for Vendure

### ISSUE THREAD

**Issue by AnthonyConklin** [Pinelab-studio/pinelab-vendure-plugins#47]
When attemping to generate preview fails with EOENT failed to spawn process phantomjs. This ended up requiring a binary install of phantom and also html-pdf.

```
# Add these lines to your Dockerfile anywhere before your entrypoint or CMD:
ENV PHANTOMJS_VERSION=2.1.1
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
RUN apk update && apk add --no-cache fontconfig curl curl-dev && \
  cd /tmp && curl -Ls https://github.com/dustinblackman/phantomized/releases/download/${PHANTOMJS_VERSION}/dockerized-phantomjs.tar.gz | tar xz && \
  cp -R lib lib64 / && \
  cp -R usr/lib/x86_64-linux-gnu /usr/lib && \
  cp -R usr/share /usr/share && \
  cp -R etc/fonts /etc && \
  curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 | tar -jxf - && \
  cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs

RUN npm install -g html-pdf
```

The other issue was text was not coming through, it was just transparent. This is because the docker container doesn't have fonts installed. You can either install the fonts your referencing inside of the invoice template OR just reference a google font (not sure how this would work if offline).

Inside of vendure admin -> invoices -> settings -> template update with the following code:

```
<!-- adding the following style to the template header -->
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

<!-- Customize the font family on body to match your google font ref -->
<body style="font-family: 'Roboto', sans-serif">
```

**Comment by AnthonyConklin** [comment]
Could probably just change the font requirement inside of the default template. And then add the docker block to the readme.

**Comment by martijnvdbrug** [comment]
Hi @AnthonyConklin thanks for this contribution.

Could you share your dockerfile? I also run Vendure in a docker container and invoice generation seems to work with just this dockerfile:

```shell
FROM node:16

# Create app directory
WORKDIR /usr/src/app

COPY . .
RUN yarn install --production
RUN yarn build

# PhantomJS fix https://github.com/bazelbuild/rules_closure/issues/351
ENV OPENSSL_CONF=/dev/null

# Run the web service on container startup.
CMD [ "yarn", "start" ]
```

**Comment by martijnvdbrug** [comment]
@AnthonyConklin Closing this one, as I can not reproduce your issue. Feel free to re-open this issue when more information arises.
