### ISSUE TITLE
Picqer plugin: transition to Shipped first

### ISSUE THREAD

**Issue by martijnvdbrug** [Pinelab-studio/pinelab-vendure-plugins#504]
The Picqer plugin is transitioning orders to Delivered on incoming webhook, skipping the Shipping state. Most projects expect the order to go from Payment Settled to Shipped to Delivered.

- [ ] Transition orders to Shipped before transitioning to Delivered (Line 401 in picqer.service.ts)
- [ ] Publish a patch of plugin
- [ ] Install patched version in the HPS project

**Comment by dalyathan** [comment]
On what ` OrderData.status` should we transition to `Shipped` @martijnvdbrug ? `processing`?
