### ISSUE TITLE
acceptBlueCustomerId should be a readonly hidden customField

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#519]
**Which plugin/repository is the issue about?**
Currently, `acceptBlueCustomerId` is an `int` field that shows up as required in the customFields. It should be `nullable` and `readonly`, perhaps event `internal`

**Describe the bug**
Current CustomFields config make it fail validation on our side. Also, we don't want people to see that field.

**To Reproduce**

1. Go to Customer edit form
2. Open customfields 

**Expected behavior**
This is an internal field, clients shouldn't see it, but admins should be able to.

**Additional context**

**Comment by martijnvdbrug** [comment]
Agreed. I have made it nullable and readonly. I've left it visible in Admin, because it can be useful to admins to see what AC customer is connected. Any downsides I am missing?
