### ISSUE TITLE
Facets Suggestion Plugin - Facets not saved.

### ISSUE THREAD

**Issue by MaartenWessels** [Pinelab-studio/pinelab-vendure-plugins#552]
**Which plugin/repository is the issue about?**
facets-suggestion-plugin

**Describe the bug**
When i try to add a new facet from the "Suggested Facets" part of product, it will be added but once i save it is gone, so I can't actually add it via the plugin.

**To Reproduce**

1. Go to 'Facets'
2. Add a new Facet and check the 'Show on product detail page' checkbox
3. Go to 'Products' and open one.
4. Scroll to the 'Suggested facets' and try adding a Facet
5. Save product

**Expected behavior**
The selected facet(s) is added to the product

**Screenshots**
At facet detail:
![image](https://github.com/user-attachments/assets/e6aba9b4-facf-442d-b7df-dda84db69979)

At product detail:
![image](https://github.com/user-attachments/assets/99513ea6-219f-487f-b727-a18906534bf8)

**Environment**

- Vendure version: 3.1.0
- Plugin version 1.1.1

**Comment by martijnvdbrug** [comment]
Thanks. Was able to reproduce it with V3.1.1. Fix will be published shortly as version 1.1.2

**Comment by MaartenWessels** [comment]
@martijnvdbrug Thanks for making the fix!
