### ISSUE TITLE
 Bug in the getters on the Order entity

### ISSUE THREAD

**Issue by anhquanduong2007** [Pinelab-studio/pinelab-vendure-plugins#62]
I am working with webhook and when i order the product i get the information. 

<pre>
OrderEvent {
       createdAt: 2022-09-23T08:26:08.231Z,
       ctx: RequestContext {
         _req: IncomingMessage {
           _readableState: [ReadableState],
           _events: [Object: null prototype],
           _eventsCount: 1,
           _maxListeners: undefined,
           socket: [Socket],
           httpVersionMajor: 1,
           httpVersionMinor: 1,
           httpVersion: '1.1',
           complete: true,
           headers: [Object],
           rawHeaders: [Array],
           trailers: {},
           rawTrailers: [],
           aborted: false,
           upgrade: false,
           url: '/',
           method: 'POST',
           statusCode: null,
           statusMessage: null,
           client: [Socket],
           _consuming: true,
           _dumped: false,
           next: [Function: next],
           baseUrl: '/shop-api',
           originalUrl: '/shop-api',
           _parsedUrl: [Url],
           params: {},
           query: {},
           res: [ServerResponse],
           sessionOptions: {},
           session: [Getter/Setter],
           body: [Object],
           _body: true,
           length: undefined,
           i18nextLookupName: 'header',
           lng: 'en-US',
           locale: 'en-US',
           language: 'en-US',
           languages: [Array],
           i18n: [I18n],
           t: [Function: bound t],
           vendureRequestContext: [RequestContext],
           vendureRequestContextMap: [Map],
           [Symbol(kCapture)]: false,
           [Symbol(RequestTimeout)]: undefined
         },
         _apiType: 'shop',
         _channel: Channel {
           token: 'hcicjrj5b5engrpps2a',
           createdAt: 2022-09-23T02:06:39.000Z,
           updatedAt: 2022-09-23T02:06:40.000Z,
           code: '__default_channel__',
           defaultLanguageCode: 'en',
           currencyCode: 'USD',
           pricesIncludeTax: false,
           id: 1,
           defaultShippingZone: [Zone],
           defaultTaxZone: [Zone]
         },
         _session: {
           cacheExpiry: 1663921865,
           id: 12,
           token: '2dfe181f6752067d8c7a8ab31f50065d2aa171c8617531ffb5af927a63f5d371',
           expires: 2023-09-23T13:16:23.791Z,
           activeOrderId: null,
           activeChannelId: 1,
           authenticationStrategy: 'native',
           user: [Object]
         },
         _languageCode: 'en',
         _isAuthorized: false,
         _authorizedAsOwnerOnly: true,
         _translationFn: [Function: bound t]
       },
       order: Order {
         code: 'BW8GLFL2B8B18ELP',
         state: 'Created',
         lines: [],
         surcharges: [],
         couponCodes: [],
         modifications: [],
         shippingAddress: {},
         billingAddress: {},
         subTotal: 0,
         subTotalWithTax: 0,
         currencyCode: 'USD',
         customer: Customer {
           createdAt: 2022-09-23T02:20:01.000Z,
           updatedAt: 2022-09-23T02:20:01.000Z,
           deletedAt: null,
           title: 'Gwendolyn Garrison',
           firstName: 'Colt',
           lastName: 'Larsen',
           phoneNumber: 'Tamekah Webb',
           emailAddress: 'customer@gmail.com',
           id: 1,
           user: [User]
         },
         channels: [ [Object] ],
         orderPlacedAt: null,
         taxZoneId: null,
         createdAt: 2022-09-23T08:26:08.000Z,
         updatedAt: 2022-09-23T08:26:08.000Z,
         active: true,
         shipping: 0,
         shippingWithTax: 0,
         id: 7,
         discounts: [Getter],
         total: [Getter],
         totalWithTax: [Getter],
         totalQuantity: [Getter],
         taxSummary: [Getter]
       },
       type: 'created'
     }
</pre>

But there is a problem that I can't get information like discounts, total, totalWithTax, totalQuantity, taxSummary and when I try to get those information, I get below error.

`[dev:*server] TypeError: this.shippingLines is not iterable`

## Here is the code i try to log out discounts:
      WebhookPlugin.init({
            httpMethod: 'POST',
            delay: 3000,<br />  
            events: [OrderEvent],  
            requestFn: (event: any) => {
                console.log(event)
                console.log(event?.order?.discounts)
                return {
                    headers: { test: '1234' },
                    body: JSON.stringify({ order: event?.order }),
                };
            },
        }),

**Comment by martijnvdbrug** [comment]
@anhquanduong2007 I understood from the Slack thread that this particular issue has been fixed [here](https://github.com/vendure-ecommerce/vendure/commit/3f469bbfde8b1cf178ac252fcbdd501079024b7f), but there are situations where you want to load more data that is not directly available on an order. I propose to also pass `Injector` as argument to the requestFn, so that you can load more data for a webhook post body.

**Comment by martijnvdbrug** [comment]
@anhquanduong2007 you can use `Injector` in your `requestFn` from [version 3.18.0](https://www.npmjs.com/package/vendure-plugin-webhook/v/3.18.0) and upwards;
```ts
...
requestFn: async (event: OrderEvent, injector: Injector) => {
      await this.entityHydrator.hydrate(event.ctx, event.order, {relations: ['lines', 'shippingLines']});
      return {
        headers: { test: '1234' },
        body: JSON.stringify({ order: event?.order }),
      };
    },
...
```
