### ISSUE TITLE
Order export plugin: Download broken due to missing Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by kyunal** [Pinelab-studio/pinelab-vendure-plugins#86]
**Which plugin is the issue about?**
Order export plugin

**Describe the bug**
Downloading exported orders may not be possible due to the browser security setting. Newer browser policies forbid script access to the Content-Disposition header which makes it impossible to gather the filename, resulting in an error.

**To Reproduce**

1. Use the latest export order plugin
2. Use a recent version of chrome
3. Download will fail despite a correct API response with "Cannot read properties of null (reading 'split')" coming from the attempted split on the not exposed HTTP header

**Expected behavior**
The controller should respond with the `Access-Control-Expose-Headers` set to `Content-Disposition` so that the browser script can access said header value

**Environment**
- Vendure version: 1.9.2
- Plugin version: 4.7.2

**Additional context**
I'm intentionally opening this as an issue before submitting a PR because this is not a field I'm well experienced in. Details about this header can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)

**Comment by martijnvdbrug** [comment]
This makes sense. The content-disposition header is accessed to get the preferred filename from the backend.
I will get to it

**Comment by martijnvdbrug** [comment]
This is a bit of an old issue now, and I cannot seem to reproduce this, so I will close this issue.
