### ISSUE TITLE
PDF Invoices not listing in Vendure

### ISSUE THREAD

**Issue by huwgit** [Pinelab-studio/pinelab-vendure-plugins#87]
**Which plugin is the issue about?**
Vendure PDF Invoices plugin

**Describe the bug**
The orders are not listing automatically under the Invoices tab. Therefore I cannot select an order and create an invoice.

**To Reproduce**
From https://pinelab-plugins.com/plugin/vendure-plugin-invoices/

1. npm install vendure-plugin-invoices
2. I updated Vendure config
3. Ran a migration 
4. allowed for AllowInvoicesPermission
5. updated docker file

I'm not sure if I've done 'Enable invoice generation for the current channel on order placement.'

Go to http://185.237.99.189/admin test site. Log in superadmin | superadmin.

**Comment by martijnvdbrug** [comment]
Are you sure you have generated invoices in the database? It seems like there are no invoices to show.

Is there any logging in your server that indicates something is wrong when an order is placed?

If possible, could you share steps to reproduce your issue on a clean Vendure install?

**Comment by huwgit** [comment]
A new install:

1. npm init @vendure my-app
2. npm install @vendure/ui-devkit
3. npm install vendure-plugin-invoices
4. Edit vendure-config:

import { compileUiExtensions } from '@vendure/ui-devkit/compiler';
import { InvoicePlugin, InvoicePlugin.ui } from 'vendure-plugin-invoices';

and in plugins

`plugins: [
  InvoicePlugin.init({
    /**
     * This plugins requires a license for commercial use.
     * Visit https://pinelab-plugins.com/vendure-plugin-invoices
     * for more information
     */
    // licenseKey: processs.env.LICENSE,
    // Used for generating download URLS for the admin ui
    vendureHost: 'http://localhost:3106',
  }),
  // Add the invoices page to the admin ui
  AdminUiPlugin.init({
    port: 3002,
    route: 'admin',
    app: compileUiExtensions({
      outputPath: path.join(__dirname, '__admin-ui'),
      extensions: [InvoicePlugin.ui],
    }),
  }),
];`

5. ts-node migration.ts generate my-migration (created successfully
6. ts-node migration.ts run
7. npm run dev
8. Enable permissions

**Comment by huwgit** [comment]
Currently running with same issue

**Comment by martijnvdbrug** [comment]
I don't see any placed orders in your test environment. Invoices are generated when an order is placed (PaymentSettled). Could that be the problem?

I have just tested the plugin with SQLite and it still generates invoices. Can you share more detailed steps to reproduce, including version numbers like specified in the issue template? I'm looking for something like this:

1. Start vendure server
2. Enable generate invoices
3. Place order (how do you place an order, what items)
4. Verify the order is in PaymentSettled state
5. Invoices are not generated.
(Please also include the database your using, Vendure version and plugin version). 

Without steps to reproduce,it's very hard for me to find out what's going wrong.

**Comment by huwgit** [comment]
NB: I did another set up, the details under testing

TESTING

1. Run the vendure server
2. Roles - order-manager - check AllowInvoicesPermission and update
3. Create an order inside admin - 

select orders
click create draft order
Add 32 inch monitor to order
Set customer
Set shipping address and method
Select complete draft button
Add payment to order - state reads payment settled

4. Check invoices at this point and nothing is listed. 

SET UP

Node v16.15.1
Npm 9.1.2

Install venture: npm init @vendure var-2601
Welcome to @vendure/create v1.8.5!
Using SQLite with test data

PDF Invoice Plugin 
npm install venture-plugin-invoices

Devkit Compiler:
Nom install @vendure/ui-devkit

Updated vendure-config.ts

import { InvoicePlugin } from 'vendure-plugin-invoices';
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';

…..

   InvoicePlugin.init({
    /**
     * This plugins requires a license for commercial use.
     * Visit https://pinelab-plugins.com/vendure-plugin-invoices
     * for more information
     */
     // licenseKey: processs.env.LICENSE,
    // Used for generating download URLS for the admin ui
    vendureHost: 'http://localhost:3106',
  }),
  // Add the invoices page to the admin ui
  AdminUiPlugin.init({
    port: 3002,
    route: 'admin',
    app: compileUiExtensions({
      outputPath: path.join(__dirname, '__admin-ui'),
      extensions: [InvoicePlugin.ui],
    }),
  }),

Run migration
ts-node migration.ts generate my-migration
Returns Migration src/migrations/1674737772721-my-migration.ts has been generated successfully.

ts-node migration.ts run
Returns Successfully ran migration: myMigration1674737772721

**Comment by huwgit** [comment]
how do I check if worker instance running?

**Comment by huwgit** [comment]
I've noticed this might be incorrect - should be ../admin-ui I think

 outputPath: path.join(__dirname, '__admin-ui'),

**Comment by huwgit** [comment]
I've been having an issue with getOrderByCode - any connection?

**Comment by martijnvdbrug** [comment]
> I've been having an issue with getOrderByCode - any connection?

Nope, the plugin definitely doesn't change anything related to getOrderByCode.

**Comment by martijnvdbrug** [comment]
It seems to be because Draft orders (or manually adding payments to orders) doesn't fire an orderPlacedEvent. Invoices are generated on Order placement, so, no event === no invoice.

This is an issue with the Vendure core. I suggest creating an issue there.

The good news is: placing an order via the shop-api (via a storefront) should work fine!

**Comment by martijnvdbrug** [comment]
https://github.com/vendure-ecommerce/vendure/issues/2014
