### ISSUE TITLE
Stripe Subscription error in email plugin

### ISSUE THREAD

**Issue by yackinn** [Pinelab-studio/pinelab-vendure-plugins#94]
**Which plugin is the issue about?**
vendure-plugin-stripe-subscription

**Describe the bug**
After the payment is settled and the confirmation email should be sent out the email plugin will throw this error.

If the vendure stripe plugin is used the error won't occur.

**To Reproduce**

1. Create an order
2. Pay the order
3. See the vendure logs

**Expected behavior**
The error should not be thrown and the order confirmation email should be sent out correctly.

**Screenshots**
![Bildschirm­foto 2023-02-04 um 11 17 22](https://user-images.githubusercontent.com/61085055/216761583-e618c874-3895-485c-9ec6-febe39cd7bbc.png)

The context doesn't yield a request object.
![Bildschirm­foto 2023-02-04 um 11 30 54](https://user-images.githubusercontent.com/61085055/216762140-4f5197e3-ab6a-4aae-a5d8-8dfaaf6d815d.png)

**Environment**

- Vendure version: 2.0.0-next.27
- Plugin version 4.4.0-beta.31
- Database Postgres

**Additional context**

**Comment by martijnvdbrug** [comment]
Thank you for the bug report! Good find. I have found the cause of this and will publish it in the next release.

You could argue that this is a bug in the EmailPlugin though: We use `new RequestContext()` in our code, and the `req` argument is optional. So, I would say a RequestContext without a `req` is still valid, and the EmailPlugin should check if a req object is there.

**Comment by yackinn** [comment]
Perfect, thank you. That's correct. It should also be handled in the email plugin. Do you want to create a bug ticket in the vendure repo?

**Comment by martijnvdbrug** [comment]
Will do

**Comment by martijnvdbrug** [comment]
Publish in v5.0.1 https://www.npmjs.com/package/vendure-plugin-stripe-subscription
